### ISSUE TITLE
Add an Anchor to the Instance Method Summary section

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/ruby-api-docs#15] opened 2016-11-19 11:21 UTC
Would it be possible to add an anchor at the Instance Method Summary Section of a class?  I want to create a browser bookmark directly to the method summary. I can not currently do this.

**Comment by jimfoltz** [comment] 2016-11-19 13:14
This could be also mitigated by the ability to collapse the Overview section.

**Comment by thomthom** [comment] 2016-11-20 15:39
We are using YARD now to generate the Ruby API docs. It's mainly the YARD default template with some custom styling to match our brand.

Adding an anchor would be possible. How much work depend on the template fragment that define it. I actually found it to often be more time consuming to figure out which template fragment control what that doing the actual change. 

I like the suggestion though.

**Comment by DanRathbun** [comment] 2016-12-13 21:04
All of the section header `<h2>` elements should be anchored and collapsible.

**Comment by jimfoltz** [comment] 2016-12-15 02:01
> I actually found it to often be more time consuming to figure out which template fragment control what that doing the actual change.

Add a HTML comment to the top of the .erb files: 
    `<!-- <%= __FILE__ %> -->`

> I like the suggestion though.

Like it enough to accept a [pull-request](https://github.com/SketchUp/sketchup-yard-template/compare/master...jimfoltz:feature/method_summary_anchor#diff-c4ac1fe83cb72cec5ba6115fcdae1569)?

**Comment by thomthom** [comment] 2016-12-15 09:24
Yes, such a pull request would be most welcome!

**Comment by jimfoltz** [comment] 2016-12-16 14:07
Submitted.

**Comment by DanRathbun** [comment] 2016-12-23 00:33
You can add a phrase such as "close #15" to your commit message, and that issue number will be closed and linked to that commit by GitHub.
*Ref:* https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by jimfoltz** [comment] 2016-12-23 11:02
> You can add a phrase such as "close #15" to your commit message, and that issue number will be closed and linked to that commit by GitHub.

True but I feel it's better to wait to close until there is consensus  it should be closed. As often as not there seems to always be another small tweak to get things correct.

**Comment by DanRathbun** [comment] 2016-12-24 03:19
I disagree, as the issue can easily be reopened if need be.
(There is a scenario in which the issue is not closed in non-default branches.)
**The important part is that the commit/merge is linked to the issue(s)**.
*Ref:* https://help.github.com/articles/closing-issues-via-commit-messages/

Using a `#number` without one of the close keywords, *might* still create an issue link, but not close the issue(s).

**Comment by DanRathbun** [comment] 2016-12-24 03:28
**Test.** Just adding in a link to the commit: https://github.com/SketchUp/ruby-api-docs/commit/e70181fbf307859bf307d6b481abd1725b3acc8a
*(Seems to work okay as a link in the issue message.)*

I then **added a note to the commit itself**, in which I reference this issue. 
GitHub then inserts an activity notice, below this note.
*Ref:* https://github.com/SketchUp/ruby-api-docs/commit/e70181fbf307859bf307d6b481abd1725b3acc8a#comments

**Comment by thomthom** [comment] 2017-01-20 05:47
Noticed an interesting way to handle anchors: http://breathe.readthedocs.io/en/latest/#_CPPv2N8NutshellD0Ev

Over over various sections of that page and see how the ¶ appear.

**Closed as completed** 2017-01-20 05:47 UTC
Labels: enhancement
